name: GO SonarCloud Workflow

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Setup GO environment
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: go build -v .
      - name: Unit tests
        run: |
          go test -v -race -bench -benchmem -timeout=120s -count=1 -cover -coverpkg=./... -coverprofile=coverage.out ./... -json > report.json &&
          ls -lah
          exit 0
#      - name: Unit tests
#        run: |
#          sudo go test ./... -coverprofile coverage.out -covermode count
#          go test -covermode=atomic -coverprofile=coverage.out ./... &&
#          sudo go tool cover -func coverage.out
      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TEST_COVERAGE_THRESHOLD: 0
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi
      - name: Archive unit tests report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.json
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.out

  sonarcloud:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download unit tests report
        uses: actions/download-artifact@v2
        with:
          name: report
      - name: Download code coverage results
        uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dproject.settings=./sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}